name: cypress-typescript-browserify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: INSTALL
      run: |
        npm ci
      env:
        CI: true
    - name: LINT, TEST, CLEAN VIDEO
      run: |
        npm run lint
        npm run test-ci
        npm run clean:video
